AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a Lambda to replicate an AWS DocumentDB collection change stream events to different targets
Parameters:
  ParamS3Bucket:
    Description: The S3 Bucket that holds the lambdas
    Type: String
  ParamS3KeyLambda1:
    Description: The S3 key for the lambda code zip file that replicates documentdb change streams
    Type: String
  ParamS3KeyLambda2:
    Description: The S3 key for the lambda code zip file that encrypts the password
    Type: String
  DocumentDBURI:
    Description: The documentDB URI
    Type: String
  MasterUsername:
    Description: The documentDB username
    Type: String
  MasterUserPassword:
    Description: The documentDB password
    Type: String
    NoEcho: true
  StateDatabase:
    Description: The database where the state collection resides
    Type: String
  StateCollection:
    Description: The collection that will store resume tokens
    Type: String
  WatchedDatabase:
    Description: The database where the watched collection resides
    Type: String
  WatchedCollection:
    Description: The collection that will be replicated
    Type: String
  SubnetIds:
    Description: The SubnetIds where the documentDB instance is deployed and where the Lambda will be deploy
    Type: List<AWS::EC2::Subnet::Id>
  VpcSecurityGroupIds:
    Description: The security groups for the Lambda
    Type: List<AWS::EC2::SecurityGroup::Id>
  SyncCount:
    Description: The state sync controller
    Type: Number
    Default: 15
  MaxLoop:
    Description: The loop controller 
    Type: Number
    Default: 45
#  KMSKey:
#    Description: The ARN of the KMS Key used to decrypt the docdb user password
#    Type: String
Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "Key to encrypt lambda variables"
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Id: key-lambda-varenvs-encryption
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: "kms:*"
            Resource: "*"
  LambdaEncryptionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: AllowLambdaToWriteLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
              - Sid: AllowLambdaToCreateLogGroups
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: KMSEncrypt
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Encrypt
                Resource: !GetAtt 'KMSKey.Arn' # Use !Ref KMSKey if KMS enter as CFN Parameter
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: AllowLambdaToWriteLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
              - Sid: AllowLambdaToCreateLogGroups
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: LambdaVPCAccessExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface
                Resource: '*'
        - PolicyName: PublishSNS
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SNSTopic
        - PolicyName: KMSDecrypt
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: !GetAtt 'KMSKey.Arn' # Use !Ref KMSKey if KMS enter as CFN Parameter
      RoleName: !Sub "DocumentDB-Monitor-${AWS::StackName}"
      Path:
        Fn::Sub: /
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: !Sub "aws-sns-${AWS::StackName}"  
  LambdaEncryptionFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref ParamS3Bucket
        S3Key: !Ref ParamS3KeyLambda2
      Description: 'Lambda to encrypt an environment variable'
      FunctionName: !Sub "aws-lambda-encryption-${AWS::StackName}"
      Handler: 'lambda_function.lambda_handler'
      MemorySize: 128
      Role:
        Fn::GetAtt: LambdaEncryptionRole.Arn
      Runtime: python3.7
      Timeout: 60
    DependsOn: SNSTopic
  EncrypterResource:
    Type: "Custom::Encrypter"
    Properties:
      ServiceToken: !GetAtt LambdaEncryptionFunction.Arn
      varToEncrypt: !Ref MasterUserPassword 
      key: !Ref KMSKey
    DependsOn: LambdaEncryptionFunction
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref ParamS3Bucket
        S3Key: !Ref ParamS3KeyLambda1
      Description: 'Lambda to replicate AWS DocumentDB change streams'
      Environment:
        Variables:
          DOCUMENTDB_URI: !Ref DocumentDBURI
          STATE_DB: !Ref StateDatabase
          STATE_COLLECTION: !Ref StateCollection
          WATCHED_DB_NAME: !Ref WatchedDatabase
          WATCHED_COLLECTION_NAME: !Ref WatchedCollection
          SNS_TOPIC_ARN_ALERT: !Ref SNSTopic
          DOCUMENTDB_USR: !Ref MasterUsername
          DOCUMENTDB_PSW: !GetAtt EncrypterResource.var
          STATE_SYNC_COUNT: !Ref SyncCount
          MAX_LOOP: !Ref MaxLoop
      FunctionName: !Sub "aws-lambda-docdb-change-streams-${AWS::StackName}"
      Handler: 'lambda_function.lambda_handler'
      MemorySize: 256
      Role:
        Fn::GetAtt: LambdaRole.Arn
      Runtime: python3.7
      Timeout: 90
      VpcConfig: 
        SecurityGroupIds: !Ref VpcSecurityGroupIds
        SubnetIds: !Ref SubnetIds
    DependsOn: EncrypterResource
  Scheduler:
    Type: AWS::Events::Rule
    Properties: 
      Description: 'Rule that triggers the Lambda function'
      Name: !Sub "aws-rule-${AWS::StackName}"
      ScheduleExpression: "rate(5 minutes)"
      State: DISABLED
      Targets: 
        - Arn: !GetAtt LambdaFunction.Arn
          Id: !Sub "id-lambda-${AWS::StackName}"
    DependsOn: LambdaFunction
Outputs:
  LambdaFunctionARN:
    Description: The ARN of the lambda function
    Value:
      !GetAtt LambdaFunction.Arn
    Export:
      Name: !Sub "aws-export-name-${AWS::StackName}"
